### ISSUE TITLE
Merge 'roofs' and 'lofts' measures list. 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#353]
When applying measures, sometimes need to change a 'loft' to a 'roof' and vice versa. 

This is because sometimes works are planned by the householder that involve moving the insulation line from the ceiling to the rafters. 

At the moment this option is locked out - you can't select a 'roof' measure when it was a 'loft' in the baseline scenario. 

Simplest solution is probably to put all 'roofs' and 'lofts' into the same list

**Comment by cagabi** [comment]
Done

**Comment by marianneURBED** [comment]
Hello, 

This doesn't seem to have quite worked. 

I can now use the 'type' drop down to change from a 'loft' to a 'roof', but only the 'loft' options are available from the menu. 

The libraries are still listed separately. 

A work-around would be to add the 'lofts' measures to the 'roof' library and vice versa - but then we end up with the problem of the same thing being in two places and getting out of sync.

**Comment by cagabi** [comment]
Done it,

Sorry I have also realized I didn't even explained what I had done. I thought that merging the libraries was too messy, it would implied duplicating the data in two different libraries or doing a proper merge into one which would require messing with existing libraries. So the solution was to allow to change the type of item in the drop down. Now the list of items is updated so everything should be working ok.

Have a look and close the issue if you are happy

**Comment by marianneURBED** [comment]
Sorry carlos, that still doesn't seem to have worked. 

When I want to apply a 'roof' measure to what was previously classed as a 'loft', this is what I see. I'me not able to select the 'roof' measures - I can only see the 'loft: 
<img width="1440" alt="screen shot 2018-04-25 at 14 50 15" src="https://user-images.githubusercontent.com/16305707/39250187-392c986e-4898-11e8-89cd-d5bd12c9404d.png">
